version: '2'
services:
    front-app:
        build:
          context: .
          dockerfile: Dockerfile
        labels:
            - front        
        ports:
            - '5000:5000'
        environment:
            NODE_ENV: development
            REACT_APP_API_HOST: '34.68.2.153'
            REACT_APP_API_PORT: ':5001'
            REACT_APP_API_ENTRY: 'graphql'