version: '3.3'

services:
  docker-app:
    container_name: SL-FrontEnd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development